# Generated by Django 2.2.1 on 2019-05-17 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='albums',
            table='musicApp_albums',
        ),
    ]
