# Generated by Django 2.2.1 on 2019-05-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0002_auto_20190518_0113'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='albums',
            table='albums',
        ),
    ]
