# Generated by Django 2.2.1 on 2019-05-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0003_auto_20190518_0114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Albums',
        ),
    ]
