# Generated by Django 2.2.1 on 2019-05-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0005_albums_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='singer',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
